### ISSUE TITLE
Can't download files

### ISSUE THREAD

**Issue by KAMG95** [gautamajay52/TorrentLeech-Gdrive#214]
I tried to download direct link to my telegram group using /leech as a reply to my direct link but I got that error
'27-Dec-20 10:38:09 - tobrot.plugins.incoming_message_fn - INFO - None
27-Dec-20 10:38:09 - tobrot.helper_funcs.download_aria_p_n - INFO - ['aria2c', '--allow-overwrite=true', '--daemon=true', '--enable-rpc', '--follow-torrent=mem', '--max-connection-per-server=10', '--min-split-size=10M', '--rpc-listen-all=false', '--rpc-listen-port=6800', '--rpc-max-request-size=1024M', '--seed-time=0', '--max-overall-upload-limit=1K', '--split=10', '--bt-stop-timeout=600']
27-Dec-20 10:38:09 - pyrogram.dispatcher - ERROR - [Errno 2] No such file or directory: 'aria2c': 'aria2c'
Traceback (most recent call last):
  File "/work/HELP/TorrentLeech-Gdrive/venv/lib/python3.7/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/work/HELP/TorrentLeech-Gdrive/tobrot/plugins/incoming_message_fn.py", line 73, in incoming_message_f
    aria_i_p = await aria_start()
  File "/work/HELP/TorrentLeech-Gdrive/tobrot/helper_funcs/download_aria_p_n.py", line 65, in aria_start
    stderr=asyncio.subprocess.PIPE
  File "/usr/local/lib/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1544, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/local/lib/python3.7/asyncio/unix_events.py", line 190, in _make_subprocess_transport
    **kwargs)
  File "/usr/local/lib/python3.7/asyncio/base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/usr/local/lib/python3.7/asyncio/unix_events.py", line 775, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'aria2c': 'aria2c'"

**Comment by usmanmughalji** [comment]
Run all these commands one by one your bot will be working fine.

sudo apt-get -y git aria2 wget curl busybox unzip unrar tar python3 ffmpeg python3-pip

wget https://rclone.org/install.sh

sudo ./install.sh

mkdir gautam

wget -O gautam/gclone.gz https://git.io/JJMSG

gzip -d gautam/gclone.gz

chmod 0775 gautam/gclone

**Comment by KAMG95** [comment]
> 
> 
> Run all these commands one by one your bot will be working fine.
> 
> sudo apt-get -y git aria2 wget curl busybox unzip unrar tar python3 ffmpeg python3-pip
> 
> wget https://rclone.org/install.sh
> 
> sudo ./install.sh
> 
> mkdir gautam
> 
> wget -O gautam/gclone.gz https://git.io/JJMSG
> 
> gzip -d gautam/gclone.gz
> 
> chmod 0775 gautam/gclone

When I write "sudo apt-get -y git aria2 wget curl busybox unzip unrar tar python3 ffmpeg python3-pip" 
I got E: Invalid operation git

**Comment by usmanmughalji** [comment]
fixed now check.

**Comment by KAMG95** [comment]
THX for helping
