### ISSUE TITLE
Gclone Problem!!

### ISSUE THREAD

**Issue by KAMG95** [gautamajay52/TorrentLeech-Gdrive#217]
Everytime I use gclone comman I face the same problem, this is logs
|"03-Jan-21 02:14:29 - tobrot.plugins.incoming_message_fn - INFO - https://drive.google.com/drive/folders/188wV6jUaiQSwlhodTt1NgGvaxmOZZIpd?usp=sharing
03-Jan-21 02:14:29 - tobrot.plugins.incoming_message_fn - INFO - 
03-Jan-21 02:14:29 - tobrot.helper_funcs.cloneHelper - INFO - ['/app/gautam/gclone', 'copy', '--config=rclone.conf', 'DRIVE:{https://drive.google.com/drive/folders/188wV6jUaiQS
wlhodTt1NgGvaxmOZZIpd?usp=sharing}', 'DRIVE:/', '-v', '--drive-server-side-across-configs', '--transfers=16', '--checkers=20']
03-Jan-21 02:14:30 - pyrogram.dispatcher - ERROR - [Errno 2] No such file or directory: '/app/gautam/gclone'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/TorrentLeech-Gdrive/tobrot/plugins/incoming_message_fn.py", line 248, in g_clonee
    await gclone.gcl()
  File "/root/TorrentLeech-Gdrive/tobrot/helper_funcs/cloneHelper.py", line 194, in gcl
    pro = await asyncio.create_subprocess_exec(
  File "/usr/local/lib/python3.9/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/local/lib/python3.9/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/local/lib/python3.9/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/local/lib/python3.9/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/local/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/app/gautam/gclone'"
I checked Clonehelper.py and the code saying "	
    async def gcl(self):
        self.lsg = await self.mess.reply_text(f"Cloning...you should wait 🤒")
        destination = f'{DESTINATION_FOLDER}'
        cmd = [
            "/app/gautam/gclone",
            "copy",
            "--config=rclone.conf",
            "DRIVE:{"f"{self.g_id}""}",
            f"DRIVE:{destination}/{self.name}",
            "-v",
            "--drive-server-side-across-configs",
            "--transfers=16",
            "--checkers=20"
        ]" 
        was kinda the problem 
        in my main folder I have folder named gautam and inside it the gclone file is here

**Comment by gautamajay52** [comment]
gclone thing is till wip. 
Read readme for more details.
