### ISSUE TITLE
can't run on Windows vps

### ISSUE THREAD

**Issue by LSOIVNE** [gautamajay52/TorrentLeech-Gdrive#229]
**too many bug with aria2c...
i download and setup the aria2c try to run it, the process stop here:**

`08-Mar-21 23:06:59 - tobrot.helper_funcs.extract_link_from_message - INFO - None
08-Mar-21 23:06:59 - tobrot.plugins.incoming_message_fn - INFO - https://xxxxx.xxx.workers.dev/2021_0305_10_xxxxB.mp4
08-Mar-21 23:06:59 - tobrot.plugins.incoming_message_fn - INFO - None
08-Mar-21 23:07:00 - tobrot.helper_funcs.download_aria_p_n - INFO - ['aria2c', '--allow-overwrite=true', '--daemon=true', '--enable-rpc', '--follow-torrent=mem', '--max-connection-per-server=10', '--min-split-size=10M', '--rpc-listen-all=false', '--rpc-listen-port=6800', '--rpc-max-request-size=1024M', '--seed-time=0', '--max-overall-upload-limit=1K', '--split=10', '--bt-stop-timeout=600']`

**i send Ctrl + C to the cmd stop it** 

`08-Mar-21 23:18:40 - root - INFO - Stop signal received (2). Exiting...
08-Mar-21 23:18:41 - tobrot.helper_funcs.download_aria_p_n - INFO - b'\n03/08 23:18:31 [\x1b[1;33mWARN\x1b[0m] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.\n\n03/08 23:18:31 [\x1b[1;32mNOTICE\x1b[0m] IPv4 RPC: listening on TCP port 6800\n\n03/08 23:18:31 [\x1b[1;32mNOTICE\x1b[0m] IPv6 RPC: listening on TCP port 6800\n\r
      \r\r                                                                               \r\r
                                                          \r\r
                           \r\r                                                                               \r\r
                                                                               \r\r
                                                \r\r
                 \r\r                                                                               \r\r
                                                                     \r\n03/08 23:18:41 [\x1b[1;32mNOTICE\x1b[0m] Shutdown sequence commencing... Press Ctrl-C again for emergency shutdown.\n\nDownload Results:\ngid   |stat|avg speed  |path/URI\n======+====+===========+=======================================================\n'
08-Mar-21 23:18:41 - tobrot.helper_funcs.download_aria_p_n - INFO - b''
08-Mar-21 23:18:41 - tobrot.plugins.incoming_message_fn - INFO - API(Client(host='http://localhost', port=6800, secret='********'))
08-Mar-21 23:18:41 - tobrot.helper_funcs.download_aria_p_n - INFO - a5e8a5444ba710be
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 108-109: character maps to <undefined>
Call stack:
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\TorrentLeech-Gdrive\tobrot\__main__.py", line 213, in <module>
    app.run()
  File "C:\Program Files\Python38\lib\site-packages\pyrogram\methods\utilities\run.py", line 63, in run
    self.stop()
  File "C:\Program Files\Python38\lib\site-packages\pyrogram\sync.py", line 51, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "C:\Program Files\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\Python38\lib\site-packages\pyrogram\dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\TorrentLeech-Gdrive\tobrot\plugins\incoming_message_fn.py", line 86, in incoming_message_f
    sagtus, err_message = await call_apropriate_function(
  File "C:\TorrentLeech-Gdrive\tobrot\helper_funcs\download_aria_p_n.py", line 155, in call_apropriate_function
    await check_progress_for_dl(
  File "C:\TorrentLeech-Gdrive\tobrot\helper_funcs\download_aria_p_n.py", line 436, in check_progress_for_dl
    await check_progress_for_dl(aria2, gid, event, previous_message)
  File "C:\TorrentLeech-Gdrive\tobrot\helper_funcs\download_aria_p_n.py", line 438, in check_progress_for_dl
    LOGGER.info(
Message: 'Downloaded Successfully: `2021_0305_10_#探花UB.mp4 (281.82 MiB)` 🤒'
Arguments: ()
08-Mar-21 23:18:56 - tobrot.helper_funcs.download_aria_p_n - INFO - Downloaded Successfully: `2021_0305_10_#探利搜UB.mp4 (281.82 MiB)` 🤒
08-Mar-21 23:19:12 - tobrot.helper_funcs.download_aria_p_n - INFO - {}
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 77-78: character maps to <undefined>
Call stack:
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\TorrentLeech-Gdrive\tobrot\__main__.py", line 213, in <module>
    app.run()
  File "C:\Program Files\Python38\lib\site-packages\pyrogram\methods\utilities\run.py", line 63, in run
    self.stop()
  File "C:\Program Files\Python38\lib\site-packages\pyrogram\sync.py", line 51, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "C:\Program Files\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\Python38\lib\site-packages\pyrogram\dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\TorrentLeech-Gdrive\tobrot\plugins\incoming_message_fn.py", line 86, in incoming_message_f
    sagtus, err_message = await call_apropriate_function(
  File "C:\TorrentLeech-Gdrive\tobrot\helper_funcs\download_aria_p_n.py", line 230, in call_apropriate_function
    final_response = await upload_to_tg(
  File "C:\TorrentLeech-Gdrive\tobrot\helper_funcs\upload_to_tg.py", line 56, in upload_to_tg
    LOGGER.info(local_file_name)
Message: '2021_0305_10_#HUB.mp4'
Arguments: ()
08-Mar-21 23:19:12 - tobrot.helper_funcs.upload_to_tg - INFO - 2021_0305_10_#探HUB.mp4
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\pyrogram\dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\TorrentLeech-Gdrive\tobrot\plugins\incoming_message_fn.py", line 86, in incoming_message_f
    sagtus, err_message = await call_apropriate_function(
  File "C:\TorrentLeech-Gdrive\tobrot\helper_funcs\download_aria_p_n.py", line 230, in call_apropriate_function
    final_response = await upload_to_tg(
  File "C:\TorrentLeech-Gdrive\tobrot\helper_funcs\upload_to_tg.py", line 90, in upload_to_tg
    if os.path.getsize(local_file_name) > TG_MAX_FILE_SIZE:
  File "C:\Program Files\Python38\lib\genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [WinError 2] The system cannot find the file specified: '2021_0305_10_#HUB.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 122-123: character maps to <undefined>
Call stack:
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\TorrentLeech-Gdrive\tobrot\__main__.py", line 213, in <module>
    app.run()
  File "C:\Program Files\Python38\lib\site-packages\pyrogram\methods\utilities\run.py", line 63, in run
    self.stop()
  File "C:\Program Files\Python38\lib\site-packages\pyrogram\sync.py", line 51, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "C:\Program Files\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\Python38\lib\site-packages\pyrogram\dispatcher.py", line 221, in handler_worker
    log.error(e, exc_info=True)
Message: FileNotFoundError(2, 'The system cannot find the file specified')
Arguments: ()
08-Mar-21 23:19:12 - pyrogram.dispatcher - ERROR - [WinError 2] The system cannot find the file specified: '似初HUB.mp4'
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\pyrogram\dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\TorrentLeech-Gdrive\tobrot\plugins\incoming_message_fn.py", line 86, in incoming_message_f
    sagtus, err_message = await call_apropriate_function(
  File "C:\TorrentLeech-Gdrive\tobrot\helper_funcs\download_aria_p_n.py", line 230, in call_apropriate_function
    final_response = await upload_to_tg(
  File "C:\TorrentLeech-Gdrive\tobrot\helper_funcs\upload_to_tg.py", line 90, in upload_to_tg
    if os.path.getsize(local_file_name) > TG_MAX_FILE_SIZE:
  File "C:\Program Files\Python38\lib\genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [WinError 2] The system cannot find the file specified: '2021_0305_10_#探报搜UB.mp4'
08-Mar-21 23:19:12 - root - INFO - Stopped 343 HandlerTasks`

**i try to add "aria2_daemon_start_cmd.append("--conf-path=aria2.conf")" into download_aria_p_n.py aria_start():**

`08-Mar-21 23:25:29 - tobrot.helper_funcs.extract_link_from_message - INFO - None
08-Mar-21 23:25:29 - tobrot.plugins.incoming_message_fn - INFO - https://tgupload.lsoivne.workers.dev/2021_0305_10_xxxxxxTHUB.mp4
08-Mar-21 23:25:29 - tobrot.plugins.incoming_message_fn - INFO - None
08-Mar-21 23:25:29 - tobrot.helper_funcs.download_aria_p_n - INFO - ['aria2c', '--conf-path=aria2.conf', '--allow-overwrite=true', '--daemon=true', '--enable-rpc', '--follow-torrent=mem', '--max-connection-per-server=10', '--min-split-size=10M', '--rpc-listen-all=false', '--rpc-listen-port=6800', '--rpc-max-request-size=1024M', '--seed-time=0', '--max-overall-upload-limit=1K', '--split=10', '--bt-stop-timeout=600']
08-Mar-21 23:25:29 - tobrot.helper_funcs.download_aria_p_n - INFO - b''
08-Mar-21 23:25:29 - tobrot.helper_funcs.download_aria_p_n - INFO - b'Configuration file aria2.conf is not found.\nUsage: aria2c [OPTIONS] [URI | MAGNET | TORRENT_FILE | METALINK_FILE]...\nPrinting options tagged with \'#help\'.\nSee \'aria2c -h#help\' to know all available tags.\nOptions:\n -h, --help[=TAG|KEYWORD]     Print usage and exit.\n                              The help messages are classified with tags. A tag\n                              starts with "#". For example, type "--help=#http"\n                              to get the usage for the options tagged with\n                              "#http". If non-tag word is given, print the usage\n
                              for the options whose name includes that word.\n\n
               Possible Values: #basic, #advanced, #http, #https, #ftp, #metalink, #bittorrent, #cookie, #hook, #file, #rpc, #checksum, #experimental, #deprecated, #help, #all\n
                 Default: #basic\n                              Tags: #basic, #help\n\nRefer to man page for more information.\n'
08-Mar-21 23:25:29 - tobrot.plugins.incoming_message_fn - INFO - API(Client(host='http://localhost', port=6800, secret='********'))
08-Mar-21 23:25:29 - tobrot.helper_funcs.download_aria_p_n - INFO - 5c5f57bde3af4bda
08-Mar-21 23:25:44 - tobrot.helper_funcs.download_aria_p_n - INFO - Download aborted.
08-Mar-21 23:26:01 - tobrot.helper_funcs.download_aria_p_n - INFO - {}`

**the Download aborted itself.**

**my pip list:**

C:\TorrentLeech-Gdrive
(venv) λ pip list
Package           Version
----------------- ----------
aiohttp           3.7.3
aria2p            0.9.1
async-lru         1.0.2
async-timeout     3.0.1
attrs             20.3.0
certifi           2020.12.5
chardet           3.0.4
colorama          0.4.4
hachoir           3.1.2
hurry.filesize    0.9
idna              3.1
loguru            0.5.3
multidict         5.1.0
Pillow            8.1.0
pip               20.1.1
pyaes             1.6.1
Pyrogram          1.1.13
PySocks           1.7.1
requests          2.25.1
setuptools        47.1.0
six               1.15.0
TgCrypto          1.2.2
typing-extensions 3.7.4.3
urllib3           1.26.3
websocket-client  0.57.0
win32-setctime    1.0.3
yarl              1.6.3
youtube-dl        2020.11.12

**Comment by AmirulAndalib** [comment]
heroku On fire 🔥
